export const projects = [
  {
    name: 'Project A',
    stack: 'React, Node.js',
    desc: 'A web application for managing tasks.',
    image: '/img/Rectangle.png',
    github_link: '',
    user_link: '',
  },
  {
    name: 'Project B',
    stack: 'Vue, Express',
    desc: 'A mobile app for tracking fitness activities.',
    image: '/img/Rectangle.png',
    github_link: '#',
    user_link: '#',
  },
  {
    name: 'Project C',
    stack: 'Angular, Django',
    desc: 'An e-commerce platform for online shopping.',
    image: '/img/Rectangle.png',
    github_link: '#',
    user_link: '#',
  },
  {
    name: 'Project C',
    stack: 'Angular, Django',
    desc: 'An e-commerce platform for online shopping.',
    image: '/img/Rectangle.png',
    github_link: '#',
    user_link: '#',
  },
  {
    name: 'Project C',
    stack: 'Angular, Django',
    desc: 'An e-commerce platform for online shopping.',
    image: '/img/Rectangle.png',
    github_link: '#',
    user_link: '#',
  },
  {
    name: 'Project C',
    stack: 'Angular, Django',
    desc: 'An e-commerce platform for online shopping.',
    image: '/img/Rectangle.png',
    github_link: '#',
    user_link: '#',
  },
  {
    name: 'Project C',
    stack: 'Angular, Django',
    desc: 'An e-commerce platform for online shopping.',
    image: '/img/Rectangle.png',
    github_link: '#',
    user_link: '#',
  },
  {
    name: 'Project C',
    stack: 'Angular, Django',
    desc: 'An e-commerce platform for online shopping.',
    image: '/img/Rectangle.png',
    github_link: '#',
    user_link: '#',
  },
]
