export const projects = [
  {
    name: 'Portfolio',
    stack: 'TypeScript, React, SCSS, Vite',
    desc: 'The site you’re looking at right now.\nI wanted to go beyond a plain template — every element is custom-made and thought through with an eye for detail, interactivity, and fun',
    image: '/img/projects/portfolio.png',
    github_link: 'https://github.com/5pr05/portfolio',
    user_link: '',
  },
  {
    name: 'Sparklook_0.1',
    stack: 'HTML, JavaScript, PHP, CSS',
    desc: 'An app for sharing your ideas and exploring others’ Created as a semester project',
    image: '/img/projects/Sparklook_0.1.png',
    github_link: 'https://github.com/5pr05/Sparklook_0.1',
    user_link: '',
  },
  {
    name: 'C0RR4',
    stack: 'Python, MicroPython, Flask, paho-mqtt, Telegram Bot API, Jinja2',
    desc: 'This is a smart home automation system designed to integrate various IoT devices, providing seamless control and interaction through multiple interfaces. This version includes basic features for device management, RFID-based automation, and Telegram bot integration',
    image: '/img/projects/corra.png',
    github_link: 'https://github.com/5pr05/C0RR4',
    user_link: '',
  },
  {
    name: 'FridgeCheck',
    stack: 'Kotlin, Jetpack Compose, Material3, Gradle',
    desc: 'This app helps you create shopping lists and set reminders so you don’t forget what to buy.  It’s built to be clean, easy to use, and friendly',
    image: '/img/projects/fridge_check.png',
    github_link: 'https://github.com/5pr05/FridgeCheck',
    user_link: '',
  },
  {
    name: 'Sparklook',
    stack: 'TypeScript, React, SCSS, Bootstrap, Vite, Firebase',
    desc: 'Originally based on a semester project, this has evolved into a full-fledged app, which lets users explore, rate, and share creative ideas',
    image: '/img/projects/Sparklook.png',
    github_link: 'wip',
    user_link: '',
  },
  {
    name: 'Myths&Dreams',
    stack: 'Java, Swing, Maven',
    desc: 'A game engine built around a story set in the dream of a boy who fell asleep reading a book about Ancient Greek myths',
    image: '/img/projects/MD.png',
    github_link: 'https://github.com/5pr05/MD-game-engine',
    user_link: '',
  },
  {
    name: 'Spros Half-Swept',
    stack: 'KiCad, FreeCAD, ZMK',
    desc: 'This project stands out from the rest as it’s hardware-focused. I built a custom split keyboard based on the Sweep Half-Swept design — the project includes the PCB, case, and firmware',
    image: '/img/projects/half_swept.png',
    github_link: 'https://github.com/5pr05/spros-half-swept',
    user_link: '',
  },
  {
    name: 'Terminal Rubik’s Cube',
    stack: 'C++',
    desc: 'Project that simulates a real Rubik’s Cube in the terminal. You can shuffle it, rotate it, and even get the solution. All via keyboard',
    image: '/img/projects/rubiks_cube.png',
    github_link: 'https://github.com/5pr05/Terminal-Rubik-s-Cube',
    user_link: '',
  },
  {
    name: 'fi.recall',
    stack: 'TypeScript, React, SCSS, Bootstrap, Vite, Firebase',
    desc: 'A tool for personal growth where users create, rate, and save curated content collections. Each set can be customized, kept private, or shared with the community',
    image: '/img/projects/fi.recall.png',
    github_link: 'wip',
    user_link: '',
  },
  {
    name: 'gradoo',
    stack: 'TypeScript, React Native, React Native Paper, Firebase',
    desc: 'A simple daily tool that helps you live more comfortably and get things done',
    image: '/img/projects/gradoo.png',
    github_link: '#',
    user_link: '#',
  },
]
